### ISSUE TITLE
"Permission denied" error

### ISSUE THREAD

**Issue by benkasminbullock** [paulfloyd/freebsd_valgrind#11] opened 2020-04-05 04:31 UTC
I got the newest version of freebsd_valgrind to compile and install on the 32 bit system but now I get the following type of error:

$ valgrind --leak-check --verbose ./hw-17.cgi 
valgrind: ./hw-17.cgi: Permission denied

The ./hw-17.cgi is functioning perfectly well though.

The --verbose option doesn't give any information:

$ valgrind --leak-check --verbose ./hw-17.cgi 
valgrind: ./hw-17.cgi: Permission denied

**Comment by paulfloyd** [comment] 2020-04-05 08:23
Thanks very much for testing. Please could you confirm that this is with FreeBSD 12.1?

Can you tell me a bit more about what 'hw-17.cgi' is and does? Do you have the same problem with a minimal C program ("int main() {}")? Do you get any output with a high level of debug/verbosity e.g., "-d -d -d -d -v -v -v -v"? I just noticed that I get a coredump with an optimized build and '-d', so running configure with "CFLAGS="-g -O0" might help.

Currently I've only tested on FreeBSD 12.1 amd64 (and also Linux to ensure that I don't break the build/regression tests on that platform) . I do intend to create a bunch of VirtualBox VMs for further testing.

As for your problem, there are 3 things that I can think of that might be the cause.

1. The security.bsd.unprivileged_proc_debug sysctl (see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220943). If this is set to 0 then Valgrind will fail to run.  When I tried this I didn't get "Permission Denied" messages, I got "--{PID}:0:procself sysctll 1" (and nothing else) on x86 and a coredump on amd64.

2. There may be an issue is with the setting of LD_PRELOAD/LD_32_PRELOAD.

Could you try undoing a change that I made yesterday?

In initimg-freebsd.c change

// @todo PJF probably won't work for x86 FreeBSD
#if defined(VGP_amd64_freebsd)
   const HChar* ld_preload      = "LD_PRELOAD=";
#else
   const HChar* ld_preload      = "LD_32_PRELOAD=";
#endif

to just

   const HChar* ld_preload      = "LD_PRELOAD=";

3. It's possible that the stack layout of x86 on x86 is not the same as x86 on amd64. This is the fundamental cause why the ports version of Valgrind no longer works on x86, and my fix is a hard coded change to the address used to create the client stack.

**Comment by benkasminbullock** [comment] 2020-04-05 08:30
On Sun, 5 Apr 2020 at 17:23, Paul Floyd <notifications@github.com> wrote:

> Thanks very much for testing. Please could you confirm that this is with
> FreeBSD 12.1?
>

No, it's the same system as mentioned before:

FreeBSD mikan 11.3-RELEASE-p6 FreeBSD 11.3-RELEASE-p6 #0: Tue Jan 28
09:37:40 UTC 2020
root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
 i386



> Can you tell me a bit more about what 'hw-17.cgi' is and does? Do you have
> the same problem with a minimal C program ("int main() {}")?
>
[ben@mikan] {17:27 08} ~ 502 $ cat > guff.c
int main() { return 0; }
[ben@mikan] {17:27 55} ~ 503 $ cc guff.c -o guff
[ben@mikan] {17:28 01} ~ 504 $ valgrind --check-memory ./guff
valgrind: ./guff: Permission denied
[ben@mikan] {17:28 11} ~ 505 $



> Do you get any output with a high level of debug/verbosity e.g., "-d -d -d
> -d -v -v -v -v"?
>

I got this:

[ben@mikan] {17:28 11} ~ 505 $ valgrind -d -d -d -d -v -v -v -v
--check-memory ./guff
--46521:1:debuglog DebugLog system started by Stage 1, level 4 logging
requested
--46521:1:launcher no tool requested, defaulting to 'memcheck'
--46521:1:launcher selected platform 'x86-freebsd'
--46521:1:launcher launching
/home/ben/software/install/lib/valgrind/memcheck-x86-freebsd
--46521:1:debuglog DebugLog system started by Stage 2 (main), level 4
logging requested
--46521:1:    main Welcome to Valgrind version 3.16.0.GIT debug logging
--46521:1:    main Checking current stack is plausible
--46521:1:    main Checking initial stack was noted
--46521:1:    main Starting the address space manager
--46521:2: aspacem                 minAddr = 0x0004000000 (computed)
--46521:2: aspacem                 maxAddr = 0x00bfbfdfff (computed)
--46521:2: aspacem                  cStart = 0x0004000000 (computed)
--46521:2: aspacem                  vStart = 0x0061dff000 (computed)
--46521:2: aspacem   suggested_clstack_end = 0x00bebfefff (computed)
--46521:2: aspacem   <<< SHOW_SEGMENTS: Initial layout (5 segments)
--46521:2: aspacem   0 segment names in 0 slots
--46521:2: aspacem   freelist is empty
--46521:2: aspacem     0: RSVN 0000000000-0003ffffff     64m ----- SmFixed
--46521:2: aspacem     1:      0004000000-0061dfefff   1501m
--46521:2: aspacem     2: RSVN 0061dff000-0061dfffff    4096 ----- SmFixed
--46521:2: aspacem     3:      0061e00000-00bfbfdfff   1501m
--46521:2: aspacem     4: RSVN 00bfbfe000-00ffffffff   1028m ----- SmFixed
--46521:2: aspacem   >>>
--46521:2: aspacem   Reading /proc/self/maps
--46521:2: aspacem   <<< SHOW_SEGMENTS: With contents of /proc/self/maps
(12 segments)
--46521:2: aspacem   1 segment names in 1 slots
--46521:2: aspacem   freelist is empty
--46521:2: aspacem   (0,4,3)
/usr/home/ben/software/install/lib/valgrind/memcheck-x86-freebsd
--46521:2: aspacem     0: RSVN 0000000000-0003ffffff     64m ----- SmFixed
--46521:2: aspacem     1:      0004000000-0037ffefff    831m
--46521:2: aspacem     2: FILE 0037fff000-0038215fff 2191360 r-x-- d=0x067
i=80731   o=0       (0,4)
--46521:2: aspacem     3: FILE 0038216000-0038216fff    4096 rw--- d=0x067
i=80731   o=2187264 (0,4)
--46521:2: aspacem     4: ANON 0038217000-0039753fff     21m rw---
--46521:2: aspacem     5:      0039754000-0061dfefff    646m
--46521:2: aspacem     6: RSVN 0061dff000-0061dfffff    4096 ----- SmFixed
--46521:2: aspacem     7:      0061e00000-00bbbfefff   1437m
--46521:2: aspacem     8: ANON 00bbbff000-00bfbdefff     63m -----
--46521:2: aspacem     9: ANON 00bfbdf000-00bfbfefff  131072 rwx--
--46521:2: aspacem    10: ANON 00bfbff000-00bfbfffff    4096 r-x--
--46521:2: aspacem    11: RSVN 00bfc00000-00ffffffff   1028m ----- SmFixed
--46521:2: aspacem   >>>
--46521:1:    main Address space manager is running
--46521:1:    main Starting the dynamic memory manager
--46521:1:mallocfr newSuperblock at 0x61E00000 (pszB 4194288)  owner
VALGRIND/core
--46521:1:mallocfr deferred_reclaimSuperblock at 0x61E00000 (pszB 4194288)
 (prev 0x0) owner VALGRIND/core
--46521:1:    main Dynamic memory manager is running
--46521:1:    main Initialise m_debuginfo
--46521:1:    main VG_(libdir) = /home/ben/software/install/lib/valgrind
--46521:1:    main Getting launcher's name ...
--46521:1:    main ... /usr/home/ben/software/install/bin/valgrind
--46521:1:    main Get hardware capabilities ...
--46521:1:   cache Autodetected cache info is sensible
--46521:1:   cache Cache info:
--46521:1:   cache   #levels = 3
--46521:1:   cache   #caches = 4
--46521:1:   cache      cache #0:
--46521:1:   cache         kind = data
--46521:1:   cache         level = 1
--46521:1:   cache         size = 32768 bytes
--46521:1:   cache         linesize = 64 bytes
--46521:1:   cache         assoc = 8
--46521:1:   cache      cache #1:
--46521:1:   cache         kind = insn
--46521:1:   cache         level = 1
--46521:1:   cache         size = 32768 bytes
--46521:1:   cache         linesize = 64 bytes
--46521:1:   cache         assoc = 8
--46521:1:   cache      cache #2:
--46521:1:   cache         kind = unified
--46521:1:   cache         level = 2
--46521:1:   cache         size = 262144 bytes
--46521:1:   cache         linesize = 64 bytes
--46521:1:   cache         assoc = 8
--46521:1:   cache      cache #3:
--46521:1:   cache         kind = unified
--46521:1:   cache         level = 3
--46521:1:   cache         size = 3145728 bytes
--46521:1:   cache         linesize = 64 bytes
--46521:1:   cache         assoc = 12
--46521:1:    main ... arch = X86, hwcaps = x86-mmxext-sse1-sse2-sse3
--46521:1:    main Getting the working directory at startup
--46521:1:    main ... /usr/home/ben
--46521:1:    main Split up command line
--46521:1:    main (early_) Process Valgrind's command line options
--46521:1:    main Create initial image
--46521:1: initimg Loading client
valgrind: ./guff: Permission denied


> I just noticed that I get a coredump with an optimized build and '-d', so
> running configure with "CFLAGS="-g -O0" might help.
>
> Currently I've only tested on FreeBSD 12.1 amd64 (and also Linux to ensure
> that I don't break the build/regression tests on that platform) . I do
> intend to create a bunch of VirtualBox VMs for further testing.
>
> As for your problem, there are 3 things that I can think of that might be
> the cause.
>
>    1.
>
>    The security.bsd.unprivileged_proc_debug sysctl (see
>    https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220943). If this is
>    set to 0 then Valgrind will fail to run. When I tried this I didn't get
>    "Permission Denied" messages, I got "--{PID}:0:procself sysctll 1" (and
>    nothing else) on x86 and a coredump on amd64.
>    2.
>
>    There may be an issue is with the setting of LD_PRELOAD/LD_32_PRELOAD.
>
> Could you try undoing a change that I made yesterday?
>
> In initimg-freebsd.c change
>
> // @todo <https://github.com/todo> PJF probably won't work for x86 FreeBSD
> #if defined(VGP_amd64_freebsd)
> const HChar* ld_preload = "LD_PRELOAD=";
> #else
> const HChar* ld_preload = "LD_32_PRELOAD=";
> #endif
>
> to just
>
> const HChar* ld_preload = "LD_PRELOAD=";
>
>    1. It's possible that the stack layout of x86 on x86 is not the same
>    as x86 on amd64. This is the fundamental cause why the ports version of
>    Valgrind no longer works on x86, and my fix is a hard coded change to the
>    address used to create the client stack.
>
>
I'll reply again when I have more information.


>

**Comment by paulfloyd** [comment] 2020-04-05 08:41
In that case this could well be a 4th possible issue

4. Changes to the fstat interface. 

Could you try changing syswrap-freebsd.c around lines 850

sizeof(struct vki_stat) -> sizeof(struct vki_freebsd11_stat)

**Comment by benkasminbullock** [comment] 2020-04-06 00:00
> Could you try changing syswrap-freebsd.c around lines 850

> sizeof(struct vki_stat) -> sizeof(struct vki_freebsd11_stat)

So far I have tried just that but it doesn't change the output:
`````
[ben@mikan] {08:58 36} ~ 515 $ ls -l `which valgrind`
-rwxr-xr-x  1 ben  ben  107644 Apr  6 08:58 /home/ben/software/install/bin/valgrind*
[ben@mikan] {08:58 44} ~ 516 $ valgrind ./guff
valgrind: ./guff: Permission denied
`````
The changes I made are these:
`````
[ben@mikan] {09:02 31} freebsd_valgrind 523 $ git diff
diff --git a/coregrind/m_syswrap/syswrap-freebsd.c b/coregrind/m_syswrap/syswrap-freebsd.c
index 43538f7a3..02229c516 100755
--- a/coregrind/m_syswrap/syswrap-freebsd.c
+++ b/coregrind/m_syswrap/syswrap-freebsd.c
@@ -849,13 +849,14 @@ PRE(sys_fstat)
    PRE_REG_READ2(long, "fstat", unsigned long, fd, struct stat *, buf);
    // @todo PJF this needs adapting for FreeBSD 11 and earlier
    // @todo PJF also is this correct for x86?
-   PRE_MEM_WRITE( "fstat(buf)", ARG2, sizeof(struct vki_stat) );
+   PRE_MEM_WRITE( "fstat(buf)", ARG2, sizeof(struct vki_freebsd11_stat) );
 }
 
 POST(sys_fstat)
 {
    // @todo PJF this needs adapting for FreeBSD 11 and earlier
-   POST_MEM_WRITE( ARG2, sizeof(struct vki_stat) );
+//   POST_MEM_WRITE( ARG2, sizeof(struct vki_stat) );
+   POST_MEM_WRITE( ARG2, sizeof(struct vki_freebsd11_stat) );
 }
 
 PRE(sys_pathconf)
`````

**Comment by benkasminbullock** [comment] 2020-04-06 00:05
I tried changing all of the vki_stat things to vki_freebsd_stat:
`````
diff --git a/coregrind/m_syswrap/syswrap-freebsd.c b/coregrind/m_syswrap/syswrap-freebsd.c
index 43538f7a3..843f43146 100755
--- a/coregrind/m_syswrap/syswrap-freebsd.c
+++ b/coregrind/m_syswrap/syswrap-freebsd.c
@@ -819,14 +819,14 @@ PRE(sys_lstat)
    PRINT("sys_lstat ( %#lx(%s), %#lx )",ARG1,(char *)ARG1,ARG2);
    PRE_REG_READ2(long, "lstat", char *, file_name, struct stat *, buf);
    PRE_MEM_RASCIIZ( "lstat(file_name)", ARG1 );
-   PRE_MEM_WRITE( "lstat(buf)", ARG2, sizeof(struct vki_stat) );
+   PRE_MEM_WRITE( "lstat(buf)", ARG2, sizeof(struct vki_freebsd11_stat) );
 }
 
 POST(sys_lstat)
 {
    vg_assert(SUCCESS);
    if (RES == 0) {
-      POST_MEM_WRITE( ARG2, sizeof(struct vki_stat) );
+      POST_MEM_WRITE( ARG2, sizeof(struct vki_freebsd11_stat) );
    }
 }
 
@@ -835,12 +835,12 @@ PRE(sys_stat)
    PRINT("sys_stat ( %#lx(%s), %#lx )",ARG1,(char *)ARG1,ARG2);
    PRE_REG_READ2(long, "stat", char *, file_name, struct stat *, buf);
    PRE_MEM_RASCIIZ( "stat(file_name)", ARG1 );
-   PRE_MEM_WRITE( "stat(buf)", ARG2, sizeof(struct vki_stat) );
+   PRE_MEM_WRITE( "stat(buf)", ARG2, sizeof(struct vki_freebsd11_stat) );
 }
 
 POST(sys_stat)
 {
-   POST_MEM_WRITE( ARG2, sizeof(struct vki_stat) );
+   POST_MEM_WRITE( ARG2, sizeof(struct vki_freebsd11_stat) );
 }
 
 PRE(sys_fstat)
@@ -849,13 +849,14 @@ PRE(sys_fstat)
    PRE_REG_READ2(long, "fstat", unsigned long, fd, struct stat *, buf);
    // @todo PJF this needs adapting for FreeBSD 11 and earlier
    // @todo PJF also is this correct for x86?
-   PRE_MEM_WRITE( "fstat(buf)", ARG2, sizeof(struct vki_stat) );
+   PRE_MEM_WRITE( "fstat(buf)", ARG2, sizeof(struct vki_freebsd11_stat) );
 }
 
 POST(sys_fstat)
 {
    // @todo PJF this needs adapting for FreeBSD 11 and earlier
-   POST_MEM_WRITE( ARG2, sizeof(struct vki_stat) );
+//   POST_MEM_WRITE( ARG2, sizeof(struct vki_stat) );
+   POST_MEM_WRITE( ARG2, sizeof(struct vki_freebsd11_stat) );
 }
 
 PRE(sys_pathconf)
@@ -1275,12 +1276,12 @@ PRE(sys_fhstat)
    PRINT("sys_fhstat ( %#lx, %#lx )",ARG1,ARG2);
    PRE_REG_READ2(long, "fhstat", struct fhandle *, fhp, struct stat *, buf);
    PRE_MEM_READ( "fhstat(fhp)", ARG1, sizeof(struct vki_fhandle) );
-   PRE_MEM_WRITE( "fhstat(buf)", ARG2, sizeof(struct vki_stat) );
+   PRE_MEM_WRITE( "fhstat(buf)", ARG2, sizeof(struct vki_freebsd11_stat) );
 }
 
 POST(sys_fhstat)
 {
-   POST_MEM_WRITE( ARG2, sizeof(struct vki_stat) );
+   POST_MEM_WRITE( ARG2, sizeof(struct vki_freebsd11_stat) );
 }
 
 PRE(sys_fhstatfs)
@@ -3272,12 +3273,12 @@ PRE(sys_fstatat)
    PRE_REG_READ3(long, "fstatat",
                  int, dfd, char *, file_name, struct stat *, buf);
    PRE_MEM_RASCIIZ( "fstatat(file_name)", ARG2 );
-   PRE_MEM_WRITE( "fstatat(buf)", ARG3, sizeof(struct vki_stat) );
+   PRE_MEM_WRITE( "fstatat(buf)", ARG3, sizeof(struct vki_freebsd11_stat) );
 }
 
 POST(sys_fstatat)
 {
-   POST_MEM_WRITE( ARG3, sizeof(struct vki_stat) );
+   POST_MEM_WRITE( ARG3, sizeof(struct vki_freebsd11_stat) );
 }
 
 PRE(sys_unlinkat)
`````
That also didn't change things:
`````
$ valgrind ~/guff
valgrind: /home/ben/guff: Permission denied
`````

**Comment by paulfloyd** [comment] 2020-04-06 21:32
My guess is that it's the call to VG_(stat) in VG_(check_executable) that is failing.

Try changing that from
```
# if (FREEBSD_VERS >= FREEBSD_12)
     struct vki_freebsd11_stat buf;
     res = VG_(do_syscall2)(__NR_freebsd11_stat, (UWord)file_name, (UWord)&buf);
#    else
    struct vki_stat buf;
     res = VG_(do_syscall2)(__NR_stat, (UWord)file_name, (UWord)&buf);
#    endif
```
to just

     struct vki_freebsd11_stat buf;
     res = VG_(do_syscall2)(__NR_freebsd11_stat, (UWord)file_name, (UWord)&buf);

**Comment by benkasminbullock** [comment] 2020-04-10 10:03
Which file am I supposed to edit?

**Comment by paulfloyd** [comment] 2020-04-10 19:45
m_libcfile.c from line 481

I just pushed a change that might fix it.

**Comment by benkasminbullock** [comment] 2020-04-11 09:14
OK I am currently at this point:
````
commit 2f945da2f6cad54b8fd5a7265b77d6e515e63335 (HEAD -> freebsd)
Author: Paul Floyd <pjfloyd@wanadoo.fr>
Date:   Fri Apr 10 21:43:38 2020 +0200

    Try to fix stat use on FreeBSD 11
````
We are now back to the good old error message:
````
$ valgrind ./guff
valgrind: I failed to allocate space for the application's stack.
valgrind: This may be the result of a very large --main-stacksize=
valgrind: setting.  Cannot continue.  Sorry.

````

**Comment by paulfloyd** [comment] 2020-04-11 09:50
I currently get the following (FreeBSD 11.3 x86 in a vbox VM):

![image](https://user-images.githubusercontent.com/17177100/79040665-59f4ca80-7bea-11ea-8391-5009191ea0cd.png)

The messages at the top of the screen are fairly serious - it means no calls to malloc new etc are recognized. I also see that the one error that is detected doesn't decode the stack.

**Comment by paulfloyd** [comment] 2020-04-11 12:29
> OK I am currently at this point:
> 
> ```
> commit 2f945da2f6cad54b8fd5a7265b77d6e515e63335 (HEAD -> freebsd)
> Author: Paul Floyd <pjfloyd@wanadoo.fr>
> Date:   Fri Apr 10 21:43:38 2020 +0200
> 
>     Try to fix stat use on FreeBSD 11
> ```
> 
> We are now back to the good old error message:
> 
> ```
> $ valgrind ./guff
> valgrind: I failed to allocate space for the application's stack.
> valgrind: This may be the result of a very large --main-stacksize=
> valgrind: setting.  Cannot continue.  Sorry.
> ```

This failure occurs when V tries to set up the client stack.

![image](https://user-images.githubusercontent.com/17177100/79043504-dc3bb980-7bff-11ea-9318-734ead46caba.png)
The picture is of the 'procstat -v' output for a running process (vim, but that probably doesn't matter).

Can you either run Valgrind under gbd or add some printfs to see what the values of clstack_end are in initimg-freebsd.c are (around line 450)? Assuming the same memory map for V then the clstack_end needs end up being something less than 0xbbbf000.

**Comment by paulfloyd** [comment] 2020-04-12 14:08
I've now created a couple of VirtualBox FreeBSD 11.3 machines (i386 and amd64). They both now work with the latest head code, so I'm closing this issue. I will open another for the client stack issue.

**Closed as completed by paulfloyd** 2020-04-12 14:08 UTC
